"""empty message

Revision ID: 088c35195101
Revises: 74bd5084c6f8
Create Date: 2025-06-16 10:32:11.786390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088c35195101'
down_revision = '74bd5084c6f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bankaccounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=222), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bankaccounts', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
