"""empty message

Revision ID: 411d365ecfe7
Revises: c799d023a822
Create Date: 2025-05-22 15:27:43.727539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411d365ecfe7'
down_revision = 'c799d023a822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
