"""empty message

Revision ID: 45c77d64562f
Revises: 088c35195101
Create Date: 2025-06-17 09:20:20.025402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45c77d64562f'
down_revision = '088c35195101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bankaccounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('format', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bankaccounts', schema=None) as batch_op:
        batch_op.drop_column('format')

    # ### end Alembic commands ###
