"""empty message

Revision ID: 9e0fef22d18f
Revises: 
Create Date: 2025-05-06 18:41:03.370912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e0fef22d18f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bankaccounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_staff', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_staff')

    with op.batch_alter_table('bankaccounts', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('account_number')

    # ### end Alembic commands ###
