"""empty message

Revision ID: d05daea2ea26
Revises: 81fb4bab841b
Create Date: 2025-06-18 09:18:57.360218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd05daea2ea26'
down_revision = '81fb4bab841b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bankaccounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bankaccounts', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
