"""empty message

Revision ID: f68671f59020
Revises: 9e0fef22d18f
Create Date: 2025-05-22 14:58:26.112009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f68671f59020'
down_revision = '9e0fef22d18f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bankaccounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bankaccounts', schema=None) as batch_op:
        batch_op.drop_column('bank_name')

    # ### end Alembic commands ###
